source 'http://artrepo.daptiv.com:8081/artifactory/api/gems/rubygems-virtual/'

gem 'chefspec'
gem 'rspec'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rspec-mocks'
gem 'chef'
gem 'foodcritic'
gem 'rubocop'
gem 'rake'
gem 'berkshelf'
