name             'resharper'
maintainer       'Shawn Neal'
maintainer_email 'sneal@sneal.net'
source_url       'https://github.com/windowschefcookbooks/resharper'
issues_url       'https://github.com/windowschefcookbooks/resharper/issues'
license          'Apache 2.0'
description      'Installs/Configures ReSharper'
version          '2.0.0'
depends          'windows'
