name             'resharper'
maintainer       'Shawn Neal'
maintainer_email 'sneal@sneal.net'
source_url       'https://github.com/windowschefcookbooks/resharper'
issues_url       'https://github.com/windowschefcookbooks/resharper/issues'
chef_version     '>= 13.0'
license          'Apache-2.0'
description      'Installs/Configures ReSharper'
version          '3.0.2'
supports         'windows'
depends          'windows'
